api-path = "iozhtest/src/main/resources/tgbot.api"
fmt-config-path = "iozhtest/src/main/resources/.scalafmt.conf"
open-enum {
    enabled = true
    exclude-types = [ "MaybeInaccessibleMessage", "IFile" ]
}
custom-encoders = {
    "RichText" = """
      implicit lazy val richtextEncoder: Encoder[RichText] = {
        case plain: RichTextPlain => Json.fromString(plain.text)
        case concat: RichTextConcat => Json.arr(concat.texts.map(_.asJson): _*)
        case other => richtextGeneratedEncoder(other)
      }
    """
}
custom-decoders = {
    "MaybeInaccessibleMessage" = """
      implicit lazy val maybeinaccessiblemessageDecoder: Decoder[MaybeInaccessibleMessage] = {
        for {
          fDate <- Decoder[Int].prepare(_.downField("date"))
          value <- fDate match {
            case 0 => Decoder[InaccessibleMessage]
            case _ => Decoder[Message]
          }
        } yield value
      }
    """
    "RichText" = """
      implicit lazy val richtextDecoder: Decoder[iozhik.OpenEnum[RichText]] = Decoder.instance { c =>
        if (c.value.isString)
          c.as[String].map(s => iozhik.OpenEnum.Known(RichTextPlain(s)))
        else if (c.value.isArray)
          c.as[List[iozhik.OpenEnum[RichText]]].map(ts => iozhik.OpenEnum.Known(RichTextConcat(ts)))
        else
          richtextGeneratedDecoder(c)
      }
    """
}
